apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-deployment
spec:
  selector:
    matchLabels:
      app: trading
  template:
    metadata:
      labels:
        app: trading
    spec:
      containers:
        - name: trading
          image: playeconomybkm.azurecr.io/play.trading:1.0.1
          env:
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: QueueSettings__GrantItemsQueueAddress
              value: queue:inventory-grant-items
            - name: QueueSettings__DebitGilQueueAddress
              value: queue:identity-debit-gil
            - name: QueueSettings__SubtractItemsQueueAddress
              value: queue:inventory-subtract-items
            - name: MongoDbSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: trading-secrets
                  key: cosmosdb-connectionstring
            - name: ServiceBusSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: trading-secrets
                  key: servicebus-connectionstring
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5006
